# Generated by Django 3.0.5 on 2020-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=2500),
        ),
    ]
