# Generated by Django 3.0.5 on 2020-06-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0004_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardiologyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='CardiologyNews/images/')),
            ],
        ),
        migrations.CreateModel(
            name='DentalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='DentalNews/images/')),
            ],
        ),
        migrations.CreateModel(
            name='DietNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='DietNews/images/')),
            ],
        ),
        migrations.CreateModel(
            name='NeurologyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='NeurologyNews/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OphthalmologyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='OphthalmologyNews/images/')),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='SurgicalNews/images/')),
            ],
        ),
    ]
